export const TRANSACTION_IMPORT_MAX_ROWS = 3000;

const BYTES_PER_KIBIBYTE = 1024;
const KIBIBYTES_PER_MEBIBYTE = 1024;

export const TRANSACTION_IMPORT_MAX_FILE_SIZE_MEBIBYTES = 5;

export const TRANSACTION_IMPORT_MAX_FILE_SIZE_BYTES =
  TRANSACTION_IMPORT_MAX_FILE_SIZE_MEBIBYTES * KIBIBYTES_PER_MEBIBYTE * BYTES_PER_KIBIBYTE;
